apiVersion: v1 
kind: ConfigMap
metadata:
  name: api-configmap
data:
  Mongo__Database: admin
  Mongo__Host: mongo-service
  Mongo__Port: "27017"
  # Mongo__User="mongouser"
  # Mongo__Password="mongopwd"